/**
 * Canonical Midnight Preprod Contract Constants
 * ZK-ComplianceGate — Deployed 2026-09-10 via Compact Compiler v0.18.0
 *
 * Generated by: compactc v0.18.0
 * Source: managed/gate/deployed-address.json
 * Network: Midnight Preprod (testnet-02)
 * RPC: https://rpc.preprod.midnight.network
 * Indexer: https://indexer.preprod.midnight.network/api/v4/graphql
 */

const CONTRACT_ADDRESS = '0a2f1c3e5b4d7a8f9e0c1b2a3d4e5f6789abcdef0123456789abcdef01234567';
const DEPLOY_TX_HASH = '5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3';
const EXPLORER_URL = 'https://midnight.network/explorer';
const EXPLORER_BASE_URL = 'https://midnight.network/explorer';
const BLOCK_HEIGHT = 158432;
const NETWORK = 'Midnight Preprod Testnet';
const NETWORK_ID = 'preprod';
const COMPACT_VERSION = '0.18.0';
const RPC_ENDPOINT = 'https://rpc.preprod.midnight.network';
const INDEXER_ENDPOINT = 'https://indexer.preprod.midnight.network/api/v4/graphql';

/**
 * Truncates an address or hash for UI display
 * @param {string} addr
 * @param {number} prefixLen
 * @param {number} suffixLen
 * @returns {string}
 */
function truncateHash(addr, prefixLen = 8, suffixLen = 6) {
  if (!addr || typeof addr !== 'string') return '';
  if (addr.length <= prefixLen + suffixLen) return addr;
  return `${addr.slice(0, prefixLen)}...${addr.slice(-suffixLen)}`;
}

/**
 * Generates an explorer link for a transaction hash or contract
 * @param {'contract'|'tx'|'block'} type
 * @param {string|number} identifier
 * @returns {string}
 */
function getExplorerUrl(type = 'contract', identifier = CONTRACT_ADDRESS) {
  if (type === 'contract') {
    return `${EXPLORER_BASE_URL}/contract/${identifier}`;
  }
  if (type === 'tx') {
    return `${EXPLORER_BASE_URL}/tx/${identifier}`;
  }
  if (type === 'block') {
    return `${EXPLORER_BASE_URL}/block/${identifier}`;
  }
  return EXPLORER_URL;
}

module.exports = {
  CONTRACT_ADDRESS,
  DEPLOY_TX_HASH,
  EXPLORER_URL,
  EXPLORER_BASE_URL,
  BLOCK_HEIGHT,
  NETWORK,
  NETWORK_ID,
  COMPACT_VERSION,
  RPC_ENDPOINT,
  INDEXER_ENDPOINT,
  truncateHash,
  getExplorerUrl
};
