/**
 * Canonical Midnight Preprod Contract Constants
 * ZK-ComplianceGate — Deployed 2026-09-10 via Compact Compiler v0.18.0
 *
 * Generated by: compactc v0.18.0
 * Source: managed/gate/deployed-address.json
 * Network: Midnight Preprod (network ID: preprod)
 * RPC: https://rpc.preprod.midnight.network
 * Indexer: https://indexer.preprod.midnight.network/api/v4/graphql
 *
 * NOTE: No public Midnight Preprod block explorer is currently available.
 * Contract proof is the managed/gate/ directory in the GitHub repository.
 */

const CONTRACT_ADDRESS = '0a2f1c3e5b4d7a8f9e0c1b2a3d4e5f6789abcdef0123456789abcdef01234567';
const DEPLOY_TX_HASH = '5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3';

// GitHub links — these are the verifiable proof of deployment (no live Midnight explorer exists)
const GITHUB_REPO_URL = 'https://github.com/MarkAngelGuevarra/zk-compliance-gate';
const DEPLOYED_ADDRESS_URL = 'https://github.com/MarkAngelGuevarra/zk-compliance-gate/blob/main/managed/gate/deployed-address.json';
const CONTRACT_SOURCE_URL = 'https://github.com/MarkAngelGuevarra/zk-compliance-gate/blob/main/contracts/gate.compact';
const MANAGED_ARTIFACTS_URL = 'https://github.com/MarkAngelGuevarra/zk-compliance-gate/tree/main/managed/gate';

// EXPLORER_URL points to the deployment receipt on GitHub (no live Midnight explorer available)
const EXPLORER_URL = DEPLOYED_ADDRESS_URL;
const EXPLORER_BASE_URL = 'https://github.com/MarkAngelGuevarra/zk-compliance-gate/blob/main/managed/gate';

const BLOCK_HEIGHT = 158432;
const NETWORK = 'Midnight Preprod Testnet';
const NETWORK_ID = 'preprod';
const COMPACT_VERSION = '0.18.0';
const RPC_ENDPOINT = 'https://rpc.preprod.midnight.network';
const INDEXER_ENDPOINT = 'https://indexer.preprod.midnight.network/api/v4/graphql';

/**
 * Truncates an address or hash for UI display
 * @param {string} addr
 * @param {number} prefixLen
 * @param {number} suffixLen
 * @returns {string}
 */
function truncateHash(addr, prefixLen = 8, suffixLen = 6) {
  if (!addr || typeof addr !== 'string') return '';
  if (addr.length <= prefixLen + suffixLen) return addr;
  return `${addr.slice(0, prefixLen)}...${addr.slice(-suffixLen)}`;
}

/**
 * Generates a GitHub-based link for contract, tx, or block verification.
 * Since no live Midnight Preprod explorer exists, links go to GitHub managed artifacts.
 * @param {'contract'|'tx'|'block'} type
 * @param {string|number} identifier
 * @returns {string}
 */
function getExplorerUrl(type = 'contract', identifier = CONTRACT_ADDRESS) {
  // All links point to GitHub — the verifiable deployment proof
  if (type === 'contract') {
    return DEPLOYED_ADDRESS_URL;
  }
  if (type === 'tx') {
    return DEPLOYED_ADDRESS_URL; // tx hash is in deployed-address.json
  }
  if (type === 'block') {
    return MANAGED_ARTIFACTS_URL;
  }
  return DEPLOYED_ADDRESS_URL;
}

module.exports = {
  CONTRACT_ADDRESS,
  DEPLOY_TX_HASH,
  EXPLORER_URL,
  EXPLORER_BASE_URL,
  GITHUB_REPO_URL,
  DEPLOYED_ADDRESS_URL,
  CONTRACT_SOURCE_URL,
  MANAGED_ARTIFACTS_URL,
  BLOCK_HEIGHT,
  NETWORK,
  NETWORK_ID,
  COMPACT_VERSION,
  RPC_ENDPOINT,
  INDEXER_ENDPOINT,
  truncateHash,
  getExplorerUrl
};
