// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED BY COMPACT COMPILER v0.18.0
// TypeScript type definitions for gate.compact
// Generated: 2026-09-10T08:42:17Z
// ─────────────────────────────────────────────────────────────────────────────

export type Uint8 = number;
export type Counter = bigint;
export type ZswapCoinPublicKey = string;
export type Boolean = boolean;

/** The public ledger state of the deployed gate contract */
export interface GateLedger {
  /** Total number of eligibility verifications performed (public counter) */
  totalChecks: Counter;
  /** Maps each verifier address to their last verification result */
  verifications: Map<ZswapCoinPublicKey, Boolean>;
}

/** Witness callbacks that must be implemented by the dApp */
export interface GateWitnesses {
  /**
   * Returns the user's private age.
   * Called LOCALLY on the prover's device — value never leaves the browser.
   */
  getPrivateAge: () => Promise<Uint8>;
}

/** Providers required to interact with Midnight Network */
export interface GateProviders {
  zkProofProvider: import('@midnight-ntwrk/midnight-js-proof-provider').ZKProofProvider;
  walletProvider: import('@midnight-ntwrk/midnight-js-wallet').WalletProvider;
  midnightProvider: import('@midnight-ntwrk/midnight-js-network-id').MidnightProvider;
}

/**
 * verifyEligibility circuit
 * Reads `privateAge` via witness; proves privateAge >= ageThreshold via ZK proof.
 * Writes ONLY the boolean result to the public ledger.
 *
 * @param providers - Network and wallet providers
 * @param ledger - Current ledger state (mutated in place)
 * @param ageThreshold - Public minimum age threshold (e.g., 18 or 21)
 */
export declare function verifyEligibility(
  providers: GateProviders,
  ledger: GateLedger,
  ageThreshold: Uint8
): Promise<{ tx: unknown; ledger: GateLedger }>;

/**
 * revokeVerification circuit
 * Removes the caller's eligibility record from the public ledger.
 */
export declare function revokeVerification(
  providers: GateProviders,
  ledger: GateLedger
): Promise<{ tx: unknown; ledger: GateLedger }>;

/**
 * getVerificationStatus circuit (read-only)
 * Returns the caller's current eligibility status without a proof or transaction.
 */
export declare function getVerificationStatus(
  providers: GateProviders,
  ledger: GateLedger
): Boolean;

/**
 * Creates the initial empty ledger state for a newly deployed gate contract.
 */
export declare function emptyLedger(): GateLedger;

/** Witness interface — override `getPrivateAge` before calling verifyEligibility */
export declare const witnesses: GateWitnesses;
