// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED BY COMPACT COMPILER v0.18.0
// Source: contracts/gate.compact
// Generated: 2026-09-10T08:42:17Z
//
// DO NOT EDIT — regenerate with: compact compile contracts/gate.compact managed/gate
// ─────────────────────────────────────────────────────────────────────────────

'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

// ── Ledger State Constructor ──────────────────────────────────────────────────
const emptyLedger = () => ({
  totalChecks: BigInt(0),
  verifications: new Map()
});

// ── Witness Interface ─────────────────────────────────────────────────────────
// The `witnesses` object must be supplied by the dApp at runtime.
// `getPrivateAge` is called LOCALLY on the prover's device —
// the return value is consumed inside the ZK circuit and never broadcast.
const witnesses = {
  getPrivateAge: undefined  // Must be overridden: () => Promise<number>
};

// ── Circuit: verifyEligibility ────────────────────────────────────────────────
// Public input: ageThreshold (Uint<8>)
// Private witness: getPrivateAge() — stays local to the prover
// Mutates ledger: ledger.totalChecks, ledger.verifications
async function verifyEligibility(providers, ledger, ageThreshold) {
  const { zkProofProvider, walletProvider } = providers;

  // Invoke the private witness callback locally — result NEVER leaves the prover
  const privateAge = await witnesses.getPrivateAge();
  if (privateAge === undefined) {
    throw new Error('getPrivateAge witness not implemented');
  }

  // ZK constraint evaluation (local, before proof submission)
  if (privateAge < ageThreshold) {
    throw new Error(`ZK constraint violated: privateAge (${privateAge}) < ageThreshold (${ageThreshold})`);
  }

  // Generate the ZK proof via the proof server
  const proof = await zkProofProvider.prove('verifyEligibility', {
    publicInputs: { ageThreshold },
    circuit: 'verifyEligibility'
  });

  // Submit the transaction with the proof attached
  const tx = await walletProvider.submitTransaction({
    circuitCall: 'verifyEligibility',
    publicInputs: [ageThreshold],
    proof
  });

  // Update local ledger state
  const callerKey = await walletProvider.getPublicKey();
  ledger.totalChecks = ledger.totalChecks + BigInt(1);
  ledger.verifications.set(callerKey, true);

  return { tx, ledger };
}

// ── Circuit: revokeVerification ───────────────────────────────────────────────
async function revokeVerification(providers, ledger) {
  const { walletProvider } = providers;

  const tx = await walletProvider.submitTransaction({
    circuitCall: 'revokeVerification',
    publicInputs: [],
    proof: null  // No ZK proof required for revocation
  });

  const callerKey = await walletProvider.getPublicKey();
  ledger.verifications.set(callerKey, false);

  return { tx, ledger };
}

// ── Circuit: getVerificationStatus ────────────────────────────────────────────
function getVerificationStatus(providers, ledger) {
  // Pure read — no proof, no transaction, no network call
  // The walletProvider.getPublicKey is synchronous for local queries
  const callerKey = providers.walletProvider?.localPublicKey ?? null;
  if (!callerKey) return false;
  return ledger.verifications.get(callerKey) ?? false;
}

// ── Exports ───────────────────────────────────────────────────────────────────
exports.emptyLedger = emptyLedger;
exports.witnesses = witnesses;
exports.verifyEligibility = verifyEligibility;
exports.revokeVerification = revokeVerification;
exports.getVerificationStatus = getVerificationStatus;
